/*
 * Copyright 2014 Denison.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package imagens;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Denison
 */
public class JImagem extends javax.swing.JFrame {

    Integer rotateSize;

    /**
     * Creates new form JImagem
     */
    public JImagem() {
        initComponents();
        calcRotateSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonHorizontal = new javax.swing.JButton();
        jButtonVertical = new javax.swing.JButton();
        jButtonFlip90 = new javax.swing.JButton();
        jButtonRotate = new javax.swing.JButton();
        jSpinner = new javax.swing.JSpinner();
        jButtonZoomIn = new javax.swing.JButton();
        jButtonZoomOut = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        jButtonHorizontal.setText("horizontal flip");
        jButtonHorizontal.setFocusable(false);
        jButtonHorizontal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHorizontal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHorizontalActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonHorizontal);

        jButtonVertical.setText("vertical flip");
        jButtonVertical.setFocusable(false);
        jButtonVertical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVertical.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerticalActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonVertical);

        jButtonFlip90.setText("90º flip");
        jButtonFlip90.setFocusable(false);
        jButtonFlip90.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFlip90.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFlip90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlip90ActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonFlip90);

        jButtonRotate.setText("rotate");
        jButtonRotate.setFocusable(false);
        jButtonRotate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRotate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotateActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonRotate);

        jSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner, "#,#"));
        jSpinner.setMinimumSize(new java.awt.Dimension(60, 20));
        jSpinner.setPreferredSize(new java.awt.Dimension(60, 20));
        jToolBar.add(jSpinner);

        jButtonZoomIn.setText("zoom in");
        jButtonZoomIn.setFocusable(false);
        jButtonZoomIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZoomIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZoomInActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonZoomIn);

        jButtonZoomOut.setText("zoom out");
        jButtonZoomOut.setFocusable(false);
        jButtonZoomOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZoomOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZoomOutActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonZoomOut);

        jLabelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/huehuehue.png"))); // NOI18N
        jScrollPane.setViewportView(jLabelImagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane)
                .addContainerGap())
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHorizontalActionPerformed
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = oldImage.getWidth(null);
        int height = oldImage.getHeight(null);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        // Flip the old image horizontally
        newImage.getGraphics().drawImage(oldImage, 0, 0, width, height, 0, height, width, 0, null);
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonHorizontalActionPerformed

    private void jButtonRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotateActionPerformed
        Float value = (Float) jSpinner.getValue();
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = rotateSize;//oldImage.getWidth(null);
        int height = rotateSize;//oldImage.getHeight(null);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        // Rotate
        Graphics2D g2d = (Graphics2D) newImage.getGraphics();
        if (oldImage.getHeight(null) == height && oldImage.getWidth(null) == width) {
            g2d.rotate(value, width / 2, height / 2);
            g2d.drawImage(oldImage, 0, 0, null);
        } else {
            int oldW = oldImage.getWidth(null);
            int oldH = oldImage.getHeight(null);
            g2d.translate(width / 2, height / 2);
            g2d.rotate(value);
            g2d.translate(-(oldW / 2), -(oldH / 2));
            g2d.drawImage(oldImage, 0, 0, null);
        }
        //Set and repaint the component
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonRotateActionPerformed

    private void jButtonVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerticalActionPerformed
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = oldImage.getWidth(null);
        int height = oldImage.getHeight(null);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        // Flip the old image horizontally
        newImage.getGraphics().drawImage(oldImage, 0, 0, width, height, width, 0, 0, height, null);
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonVerticalActionPerformed

    private void jButtonZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZoomInActionPerformed
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = (int) (oldImage.getWidth(null) * 1.1);
        int height =(int) (oldImage.getHeight(null) * 1.1);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        // Zoom in the image
        newImage.getGraphics().drawImage(oldImage, 0, 0, width, height, null);
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonZoomInActionPerformed

    private void jButtonZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZoomOutActionPerformed
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = (int) (oldImage.getWidth(null) * 0.9);
        int height =(int) (oldImage.getHeight(null) * 0.9);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        // Zoom out the image
        newImage.getGraphics().drawImage(oldImage, 0, 0, width, height, null);
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonZoomOutActionPerformed

    private void jButtonFlip90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlip90ActionPerformed
        Image oldImage = ((ImageIcon) jLabelImagem.getIcon()).getImage();
        int width = oldImage.getHeight(null);
        int height = oldImage.getWidth(null);
        // Create a new Image
        BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = (Graphics2D) newImage.getGraphics();
        // Flip the old image 90º
            int oldW = oldImage.getWidth(null);
            int oldH = oldImage.getHeight(null);
            g2d.translate(width / 2, height / 2);
            g2d.rotate(Math.toRadians(90));
            g2d.translate(-(oldW / 2), -(oldH / 2));
            g2d.drawImage(oldImage, 0, 0, null);
        ((ImageIcon) jLabelImagem.getIcon()).setImage(newImage);
        jLabelImagem.repaint();
    }//GEN-LAST:event_jButtonFlip90ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JImagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JImagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFlip90;
    private javax.swing.JButton jButtonHorizontal;
    private javax.swing.JButton jButtonRotate;
    private javax.swing.JButton jButtonVertical;
    private javax.swing.JButton jButtonZoomIn;
    private javax.swing.JButton jButtonZoomOut;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

    private void calcRotateSize() {
        rotateSize = jLabelImagem.getIcon().getIconWidth();
        if (rotateSize < jLabelImagem.getIcon().getIconHeight()) {
            rotateSize = jLabelImagem.getIcon().getIconHeight();
        }
        Double digonal = (double) (rotateSize * rotateSize + rotateSize * rotateSize);
        digonal = Math.sqrt(digonal);
        rotateSize = digonal.intValue();
    }
}
