/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package editorjava;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author denison
 */
public class EditorJanela extends javax.swing.JFrame {

    private final DocumentColor docJava;
    private File arquivo;

    /**
     * Creates new form EditorJanela
     */
    public EditorJanela() {
        docJava = new DocumentColor();
        initComponents();
        docJava.configurarTextComponent(jTextPane1);
        jScrollPane3.setRowHeaderView(docJava.getLinhas());
        jScrollPane3.setColumnHeaderView(docJava.getCursor());
        //jLabel1 = docJava.getIndicarPosicao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButtonAbrir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.setViewportView(jTextPane1);

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addGap(0, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrir)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (arquivo == null) {
            int escolha = jFileChooser1.showSaveDialog(this);
            if (escolha == JFileChooser.APPROVE_OPTION) {
                File arquivoEscolhido = jFileChooser1.getSelectedFile();
                if (!arquivoEscolhido.getName().endsWith(".java")) {
                    arquivoEscolhido = new File(arquivoEscolhido.toString() + ".imsx");
                }
                arquivo = arquivoEscolhido;
            }
        }
        if (arquivo != null) {
            FileWriter arquivoFonte;
            try {
                arquivoFonte = new FileWriter(arquivo);
                arquivoFonte.write(jTextPane1.getText()); //grava no arquivo o codigo-fonte Java
                arquivoFonte.close();
                setTitle(arquivo.getName());
                JOptionPane.showMessageDialog(this, "Arquivo Salvo com sucesso!");
            } catch (IOException ex) {
                Logger.getLogger(EditorJanela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        int escolha = jFileChooser1.showOpenDialog(this);
        if (escolha == JFileChooser.APPROVE_OPTION) {
            File arquivoEscolhido = jFileChooser1.getSelectedFile();
            if (!arquivoEscolhido.isDirectory() && arquivoEscolhido.getName().endsWith(".java")) {
                try {
                    if (docJava.getLength() > 0) {
                        docJava.remove(0, docJava.getLength());
                    }
                    FileReader fileInput = new FileReader(arquivoEscolhido);
                    BufferedReader leitor = new BufferedReader(fileInput);
                    StringBuilder buffer = new StringBuilder();
                    String linha = leitor.readLine();
                    while (linha != null) {
                        buffer.append(linha);
                        buffer.append('\n');
                        linha = leitor.readLine();
                    }
                    docJava.insertString(0, buffer.toString(), null);
                    setTitle(arquivoEscolhido.getName());
                    arquivo = arquivoEscolhido;
                } catch (BadLocationException | IOException ex) {
                    JOptionPane.showMessageDialog(this, "Não foi possível abrir o arquivo\n" + arquivoEscolhido);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível abrir o arquivo\n" + arquivoEscolhido);
            }
        }
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (docJava.getLength() > 0) {
                docJava.remove(0, docJava.getLength());
            }
            arquivo = null;
            setTitle("Arquivo Novo*");
        } catch (BadLocationException ex) {
            Logger.getLogger(EditorJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorJanela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
